import argparse
import json
import os
import re
import textwrap
import urllib.request
from datetime import datetime, timezone

from readme_blocks import replace_block
from update_playbook_posts import DEFAULT_RSS_URL, fetch_rss, parse_posts


USERNAME = "IdkwhatImD0ing"
START = "<!-- CURRENTLY_BUILDING:START -->"
END = "<!-- CURRENTLY_BUILDING:END -->"


def request_json(url: str, token: str | None = None) -> list[dict]:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "github-profile-readme-updater",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def fetch_recent_activity(username: str, token: str | None) -> list[str]:
    events = request_json(f"https://api.github.com/users/{username}/events/public?per_page=30", token)
    summaries: list[str] = []

    for event in events[:18]:
        event_type = event.get("type", "Event")
        repo = event.get("repo", {}).get("name", "unknown/repo")
        payload = event.get("payload", {})

        if event_type == "PushEvent":
            commits = payload.get("commits", [])
            messages = [commit.get("message", "").splitlines()[0] for commit in commits[:2]]
            if messages:
                summaries.append(f"Pushed {len(commits)} commit(s) to {repo}: {'; '.join(messages)}")
            else:
                summaries.append(f"Pushed updates to {repo}")
        elif event_type == "PullRequestEvent":
            action = payload.get("action", "updated")
            title = payload.get("pull_request", {}).get("title", "a pull request")
            summaries.append(f"{action.title()} PR in {repo}: {title}")
        elif event_type == "IssuesEvent":
            action = payload.get("action", "updated")
            title = payload.get("issue", {}).get("title", "an issue")
            summaries.append(f"{action.title()} issue in {repo}: {title}")
        elif event_type == "CreateEvent":
            ref_type = payload.get("ref_type", "resource")
            summaries.append(f"Created {ref_type} in {repo}")
        elif event_type == "WatchEvent":
            summaries.append(f"Starred {repo}")
        else:
            summaries.append(f"{event_type.replace('Event', '')} activity in {repo}")

    return summaries[:12]


def fetch_recent_posts() -> list[str]:
    try:
        _, _, posts = parse_posts(fetch_rss(DEFAULT_RSS_URL), 3)
    except Exception as error:  # The GitHub activity summary is still useful if RSS is down.
        return [f"RSS unavailable: {error}"]

    return [f"{post['title']} - {post['description']}" for post in posts]


def fallback_summary(activity: list[str], posts: list[str]) -> str:
    bullets = []
    if activity:
        bullets.append(f"- Recent GitHub activity: {activity[0]}")
    if len(activity) > 1:
        bullets.append(f"- Also active on: {activity[1]}")
    if posts:
        bullets.append(f"- Latest writing: {posts[0]}")
    bullets.append("- Current focus: shipping AI-first hackathon tools, voice demos, and practical builder playbooks.")
    return "\n".join(bullets[:4])


def call_openai(activity: list[str], posts: list[str], api_key: str) -> str:
    model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    prompt = f"""
Write a concise GitHub profile README section called "Currently building" for Bill Zhang.

Rules:
- Return markdown bullets only.
- Use 3 to 5 bullets.
- Be concrete, direct, and credible.
- Do not use emoji.
- Do not mention private data, API keys, or that this was generated by AI.
- Do not invent accomplishments beyond the context.
- Keep each bullet under 140 characters.

Date: {today}

Recent public GitHub activity:
{chr(10).join(f"- {item}" for item in activity) or "- No recent public activity found."}

Recent Hackathon Playbook posts:
{chr(10).join(f"- {item}" for item in posts) or "- No recent posts found."}
""".strip()

    body = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": "You write concise, truthful profile copy for a developer README.",
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.4,
    }
    request = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "github-profile-readme-updater",
        },
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.loads(response.read().decode("utf-8"))

    content = payload["choices"][0]["message"]["content"].strip()
    content = re.sub(r"```(?:markdown)?|```", "", content).strip()
    if START in content or END in content:
        raise ValueError("Generated content unexpectedly contained README markers")
    return content


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--readme", default="README.md")
    parser.add_argument("--fallback-only", action="store_true")
    args = parser.parse_args()

    github_token = os.environ.get("GITHUB_TOKEN")
    openai_key = os.environ.get("OPENAI_API_KEY")
    require_openai = os.environ.get("REQUIRE_OPENAI", "0") == "1"

    activity = fetch_recent_activity(USERNAME, github_token)
    posts = fetch_recent_posts()

    if args.fallback_only:
        summary = fallback_summary(activity, posts)
    elif openai_key:
        summary = call_openai(activity, posts, openai_key)
    elif require_openai:
        raise RuntimeError("OPENAI_API_KEY is required when REQUIRE_OPENAI=1")
    else:
        summary = fallback_summary(activity, posts)

    summary = textwrap.dedent(summary).strip()
    changed = replace_block(args.readme, START, END, summary)
    print("Updated currently building block" if changed else "Currently building block already current")


if __name__ == "__main__":
    main()
